apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    otel: 
      endpointAddress: localhost:4318
      protocol: http
      isSecure: false
      stdout: true